### ISSUE TITLE
HypersimDataset is missing

### ISSUE THREAD

**Issue by brotherofken** [nianticlabs/implicit-depth#1]
Hi there!

I wanted to express my gratitude for making your research results publicly available and for releasing the source code.

While digging through the code base, I noticed that the implementation of `HypersimDataset` is missing but mentioned in the [dataset_utils.py](https://github.com/nianticlabs/implicit-depth/blob/525f7dbadcb67f36eb10035c3441a11fc2e28b31/utils/dataset_utils.py#L57). I wanted to confirm whether this omission is intentional or if it occurred inadvertently during the process of making the code publicly available.

Best regards,
Rasim.

**Comment by mohammed-amr** [comment]
Hello Rasim,

We're planning on releasing a HyperSim dataset class soon. Hang tight!

Mohamed

**Comment by brotherofken** [comment]
That will be extremely helpful!

Right now I'm working on Hypersim converter by myself and have encountered a few issues which have to be adressed carefully.

1. Firstly, the depth maps seem to contain distance to the camera center instead of the actual depth. 
  https://github.com/apple/ml-hypersim/issues/9
2. Secondly, there are a few scenes with corrupted frames, which need to be excluded. 
  https://github.com/apple/ml-hypersim/issues/22#issuecomment-888614249 which have to be excluded.
3. Per scene intrincics must be used as prescribed here: https://github.com/apple/ml-hypersim/tree/main/contrib/mikeroberts3000
  upd. actually one has to reproject tilt-shifted images to bring intrinsics matrix to "standart" form.
4. Not an issue, but tonemapping needs to be applied.
  https://github.com/apple/ml-hypersim/blob/main/code/python/tools/scene_generate_images_tonemap.py#L76

If you have a spare minute, could you please let me know if there are any other important details that I might be missing?

**Comment by qureshizawar** [comment]
Hi, sorry for the delay! We have just merged the Hypersim code, please check the README! :)
