### ISSUE TITLE
sr_bd_high_res_sup_pretrained_7525.yaml is missing

### ISSUE THREAD

**Issue by sdfsfwe** [nianticlabs/implicit-depth#2]
Hello!

I wanted to express my gratitude for making your research results publicly available, and your work is truly amazing! 

However, I have a few questions. I noticed that the sr_bd_high_res_sup_pretrained_7525.yaml, which is required for the inference implementation, is missing. If I have overlooked something, I hope you can provide some helpful advice.

Best regards,
wb

**Comment by JamieWatson683** [comment]
Hi - sorry for the delay!

Good catch, I think that's a bug in the readme. You should use one of `implicit_depth.yaml` or `implicit_depth_temporal.yaml` depending on which model you are running.

I'll update the readme if you confirm it works!

Thanks a lot
